name: Project Buhay Test and Review

on:
  push:
    branches:
      - main
  
  pull_request_target:
    branches:
      - main

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
        
      - name: Check Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv 

      - name: Start FastAPI server
        env:
          DB_CACHE_NAME: ${{ secrets.DB_CACHE_NAME }}
          DB_CACHE_USER: ${{ secrets.DB_CACHE_USER }}
          DB_CACHE_PASSWORD: ${{ secrets.DB_CACHE_PASSWORD }}
          DB_CACHE_HOST: ${{ secrets.DB_CACHE_HOST }}
          DB_CACHE_PORT: ${{ secrets.DB_CACHE_PORT }}
          DB_CACHE_TABLE_NAME: ${{ secrets.DB_CACHE_TABLE_NAME }}
          DB_CACHE_URL: ${{ secrets.DB_CACHE_URL }}
          GOOGLE_MAPS_API: ${{ secrets.GOOGLE_MAPS_API }}
        run: |
          nohup uvicorn main:app --host 127.0.0.1 --port 8000 & # run in background
          sleep 5 # wait to start

      - name: Run pytest with secrets
        env:
          DB_CACHE_NAME: ${{ secrets.DB_CACHE_NAME }}
          DB_CACHE_USER: ${{ secrets.DB_CACHE_USER }}
          DB_CACHE_PASSWORD: ${{ secrets.DB_CACHE_PASSWORD }}
          DB_CACHE_HOST: ${{ secrets.DB_CACHE_HOST }}
          DB_CACHE_PORT: ${{ secrets.DB_CACHE_PORT }}
          DB_CACHE_TABLE_NAME: ${{ secrets.DB_CACHE_TABLE_NAME }}
          DB_CACHE_URL: ${{ secrets.DB_CACHE_URL }}
          GOOGLE_MAPS_API: ${{ secrets.GOOGLE_MAPS_API }}
        run: |
          pytest --maxfail=5 --disable-warnings